sudo xbps-install -Syu &&

sudo xbps-install -Sy \
    xorg-minimal \
    xorg-fonts \
    xf86-input-synaptics \
    xf86-input-evdev \
    xf86-video-intel \
    alsa-utils \
    openntpd \
    simple-mtpfs \
    base-devel \
    libXft-devel \
    libXinerama-devel \
    wireless_tools \
    xdg-utils \
    xbacklight \
    xwinwrap \
    tlp \
    xmodmap \
    xrandr \
    xrdb \
    xtitle \
    xclip \
    xprop \
    lm_sensors \
    rsync \
    curl \
    wget \
    bluez \
    bspwm \
    sxhkd \
    polybar \
    neovim \
    git \
    stow \
    youtube-dl \
    feh \
    scrot \
    mpv \
    ranger \
    rxvt-unicode \
    compton \
    zsh \
    rofi \
    dmenu \
    firefox \
    telegram-desktop \
    nodejs \
    vscode \
    python3 \
    python3-pip \
    font-Siji \
    termsyn-font
