#!/bin/sh

#LAUNCHERS
$HOME/.config/polybar/launch.sh
$HOME/.config/bspwm/external_monitor.sh

# wallpaper
# hsetroot -full ~/Pictures/wallpapers/wallpaper1.jpg &
feh --bg-center ~/Pictures/wallpapers/wallpaper1.jpg ~/Pictures/wallpapers/wallpaper1.jpg


# compton
pkill compton
compton &

#BSPWM configuration
#bspc config border_radius       8
bspc config border_width         2
bspc config window_gap           10
bspc config top_padding          30
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10
bspc config single_monocle       false
bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config focus_follows_pointer true
bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color 	"#dd2727"


#Single monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#Dual monitor
#find out names with arandr or xrandr
bspc monitor HDMI1 -d 1 2 3 4 5
bspc monitor LVDS1 -d 6 7 8 9 10

#Fullscreen applications
bspc rule -a Vlc state=fullscreen

#Floating applications
bspc rule -a Galculator state=floating

#Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled

#open applications on specific workspaces
# bspc rule -a  Brave-browser desktop='^1' follow=on
# bspc rule -a  Code desktop='^2' follow=on
# bspc rule -a  TelegramDesktop desktop='^1'  follow=on
